# Generated by Django 5.1.4 on 2026-07-10 18:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Salary (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal (₹)')),
                ('tenure_months', models.IntegerField(verbose_name='Tenure (months)')),
                ('annual_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Annual Interest Rate (%)')),
                ('emi_amount', models.DecimalField(decimal_places=2, help_text='Auto-calculated on loan creation', max_digits=12, verbose_name='Monthly EMI (₹)')),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Outstanding Principal (₹)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('FORECLOSED', 'Foreclosed')], default='ACTIVE', max_length=15)),
                ('disbursed_on', models.DateField(verbose_name='Disbursement Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField(verbose_name='EMI #')),
                ('due_date', models.DateField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='EMI Amount (₹)')),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal (₹)')),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest (₹)')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Outstanding After (₹)')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.loan')),
            ],
            options={
                'verbose_name': 'EMI Schedule Row',
                'ordering': ['emi_number'],
                'unique_together': {('loan', 'emi_number')},
            },
        ),
    ]
